services:
  rabbitmq:
    image: rococo_sample_rabbitmq
    container_name: rococo_sample_rabbitmq
    build:
      context: ./services/rabbitmq
      dockerfile: Dockerfile
    volumes:
      - rococo-sample-rabbitmq-data:/var/lib/rabbitmq/mnesia/
    networks:
        - backnet
    env_file:
    - .env.secrets
    - ${APP_ENV}.env
    ports:
    - "5672:5672"
    expose:
    - "5672"
    healthcheck:
        test: rabbitmq-diagnostics -q ping
        timeout: 20s
        retries: 10

  postgres:
    image: rococo_sample_postgres
    platform: linux/amd64
    container_name: rococo_sample_postgres
    build:
      context: ./services/postgres
      dockerfile: Dockerfile
    user: "1000:50"
    restart: always
    networks:
      - backnet
    env_file:
      - .env.secrets
      - ${APP_ENV}.env
    volumes:
        - rococo-sample-postgres-data:/var/lib/postgresql/data
    ports:
        - "5432:5432"
    healthcheck:
        test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
        timeout: 20s
        retries: 10
    expose:
        - 5432
    user: postgres

  api:
    restart: always
    image: rococo_sample_api
    container_name: rococo_sample_api
    build:
        context: .
        dockerfile: ./flask/Dockerfile
    volumes:
      - ./flask:/api
      - ./common:/api/common
    ports:
      - '5000:5000'
    env_file:
      - .env.secrets
      - ${APP_ENV}.env
    depends_on:
      postgres:
          condition: service_healthy
      rabbitmq:
          condition: service_healthy
    networks:
      - backnet

volumes:
  rococo-sample-postgres-data:
    name: rococo-sample-postgres-data
  rococo-sample-rabbitmq-data:
    name: rococo-sample-rabbitmq-data
    driver: local

networks:
  backnet:
